name: Metrics

on:
  schedule: [{ cron: "0 * * * *" }] # every hour
  workflow_dispatch:

jobs:
  calendar-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jct-05
          base: ""
          plugin_calendar: yes
          plugin_calendar_limit: 1
          filename: metrics.plugin.calendar.svg

  languages-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v3.33
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jct-05
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: github-metrics
          plugin_languages_details: bytes-size, percentage
          plugin_languages_threshold: 2%
          filename: metrics.plugin.languages.svg
